name: Versioning

on:
  [push]
  
env:
  PROJECT_PATH: 'Pipeline.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: ğŸ› Checkout repo
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: ğŸš§ Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: âš™ï¸ Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: âš™ï¸ Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - run: |
          echo "PreReleaseTag: ${{ steps.gitversion.outputs.preReleaseTag }}"
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
          
      - name: ğŸ§± Build project
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.semVer }} -p:Version=${{ steps.gitversion.outputs.semVer }}

      # create symbols package https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg
      # non
      - name: ğŸ“¦ Create the package
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.gitversion.outputs.semVer }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
        
      - name: ğŸ“‘ Dotnet NuGet Add Source
        run: dotnet nuget add source --username sonomirco --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/sonomirco/index.json"
    
      - name: ğŸš€ Publish the package
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
